CREATE TABLE employees (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(100) NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    finished DATETIME
);